apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: bold-services

resources:
  - ../boldbi-manifests

configMapGenerator:
- name: bold-bi-config
  namespace: bold-services
  literals:
    - APP_BASE_URL=<your_updated_application_base_url>
    - BOLD_SERVICES_HOSTING_ENVIRONMENT=k8s
    - INSTALL_OPTIONAL_LIBS=mongodb,mysql,influxdb,snowflake,oracle,clickhouse,google
    
images:
  - name: gcr.io/boldbi-294612/boldbi-server-api
    newTag: 7.4.11
    
  - name: gcr.io/boldbi-294612/boldbi-server-jobs
    newTag: 7.4.11

  - name: gcr.io/boldbi-294612/boldbi-server
    newTag: 7.4.11
    
  - name: gcr.io/boldbi-294612/boldbi-designer
    newTag: 7.4.11

  - name: gcr.io/boldbi-294612/bold-etl
    newTag: 7.4.11
    
  - name: gcr.io/boldbi-294612/bold-identity-api
    newTag: 7.4.11
   
  - name: gcr.io/boldbi-294612/bold-ums
    newTag: 7.4.11

  - name: gcr.io/boldbi-294612/bold-identity
    newTag: 7.4.11