apiVersion: v1
kind: Secret
metadata:  
  name: bold-license-key
  namespace: bold-services
type: Opaque
stringData:
  #  The Bold BI licnece key which you have purchesed.
  BOLD_SERVICES_UNLOCK_KEY: ""
